name = "KLPQ Music Radio"
prefix = "klpq"
mainprefix = "z"

[properties]
author = "Rebel"
url = "https://github.com/rebelvg"

[files]
include = [
    "mod.cpp",
    "mod.paa"
]
exclude = [
  "README.md"
]

[version]
major = 1
minor = 1
patch = 2
build = 0

[hemtt.launch.default]
workshop = [
  "450814997" # CBA
]
presets = []
dlc = []
optionals = []
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching"
]
